name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust
      uses: crusty-pie/toolchain@main
      with:
        toolchain: stable
        override: true
    - name: Run tests
      run: cargo test --manifest-path Cargo.toml

